version: '3'

networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports: 
      - "8000:80"
    volumes:
      - ./src:/var/www/html:delegated
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:delegated
    depends_on: 
      - php
      - mysql
    networks: 
      - laravel

  php:
    build:
      context: .
      dockerfile: php.dockerfile
      target: php_base
    container_name: php
    volumes:
      - ./src:/var/www/html:delegated
    expose:
      - "9000"
    networks:
      - laravel

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql:delegated
    ports:
      - "3306:3306"
    environment: 
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      SERVICE_NAME: mysql
    networks:
      - laravel

  cron:
    build:
      context: .
      dockerfile: php.dockerfile
      target: php_cron
    container_name: cron
    restart: unless-stopped
    volumes:
      - ./sites:/var/www/html
    networks:
      - laravel
  
  supervisor:
    build:
      context: .
      dockerfile: php.dockerfile
      target: php_supervisor
    container_name: supervisor
    volumes:
      - ./src:/var/www/html:delegated
    networks:
      - laravel
  
  redis:
    build:
      context: .
      dockerfile: php.dockerfile
      target: php_redis
    container_name: redis
    volumes:
      - ./src:/var/www/html:delegated
    expose:
      - "6379"
    networks:
      - laravel
      